"use client";
import { FormEvent, useEffect, useState } from "react";
import { authApi } from "@/lib/api";

export default function AuthGate({ onAuthenticated }: { onAuthenticated: () => Promise<void> }) {
  const [mode, setMode] = useState<"login" | "register">("login"); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [pending, setPending] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { authApi.restore().then(onAuthenticated).catch(() => undefined).finally(() => setPending(false)); }, [onAuthenticated]);
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(null); setPending(true); try { if (mode === "login") await authApi.login(email, password); else await authApi.register(name, email, password); await onAuthenticated(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not authenticate"); } finally { setPending(false); } };
  if (pending) return <main className="grid h-screen place-items-center bg-zinc-50 text-sm text-zinc-500">Connecting to Forge…</main>;
  return <main className="grid min-h-screen place-items-center bg-zinc-100 p-6"><form onSubmit={submit} className="w-full max-w-md rounded-2xl border border-zinc-200 bg-white p-8 shadow-sm"><div className="mb-7"><div className="text-2xl font-bold tracking-tight">Forge</div><p className="mt-2 text-sm text-zinc-500">{mode === "login" ? "Sign in to your workspace." : "Create a personal Forge workspace."}</p></div>{mode === "register" && <label className="mb-4 block text-sm font-medium">Name<input required value={name} onChange={(e) => setName(e.target.value)} className="mt-1.5 w-full rounded-lg border border-zinc-300 px-3 py-2.5 font-normal outline-none focus:border-zinc-900" /></label>}<label className="mb-4 block text-sm font-medium">Email<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="mt-1.5 w-full rounded-lg border border-zinc-300 px-3 py-2.5 font-normal outline-none focus:border-zinc-900" /></label><label className="mb-5 block text-sm font-medium">Password<input required minLength={8} type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="mt-1.5 w-full rounded-lg border border-zinc-300 px-3 py-2.5 font-normal outline-none focus:border-zinc-900" /></label>{error && <p className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={pending} className="w-full rounded-lg bg-zinc-900 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{mode === "login" ? "Sign in" : "Create account"}</button><button type="button" onClick={() => { setMode(mode === "login" ? "register" : "login"); setError(null); }} className="mt-4 w-full text-sm text-zinc-600 underline">{mode === "login" ? "Need an account? Register" : "Already have an account? Sign in"}</button></form></main>;
}
